config/routes.rb
# == Route Map
#
Rails.application.routes.draw do
  resources :variation_weights
  get "welcome/index"

  root "welcome#index"
  get "cadastrando_dados", to: "welcome#create_person", as: :first_login

  get "dashboard/:id", to: "dashboard#index", as: :dashboard
  get "dashboard/:id/diet_menu", to: "dashboard#menu_diet", as: :diet_dashboard

  resources :people
  resources :meals
  resources :diets

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/variation_weight.rb
class VariationWeight < ApplicationRecord
  belongs_to :person
end

app/controllers/variation_weights_controller.rb
class VariationWeightsController < ApplicationController
  before_action :set_variation_weight, only: %i[ show edit update destroy ]

  # GET /variation_weights or /variation_weights.json
  def index
    @variation_weights = VariationWeight.all
  end

  # GET /variation_weights/1 or /variation_weights/1.json
  def show
  end

  # GET /variation_weights/new
  def new
    @variation_weight = VariationWeight.new
  end

  # GET /variation_weights/1/edit
  def edit
  end

  # POST /variation_weights or /variation_weights.json
  def create
    @variation_weight = VariationWeight.new(variation_weight_params)

    respond_to do |format|
      if @variation_weight.save
        format.html { redirect_to @variation_weight, notice: "Variation weight was successfully created." }
        format.json { render :show, status: :created, location: @variation_weight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @variation_weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variation_weights/1 or /variation_weights/1.json
  def update
    respond_to do |format|
      if @variation_weight.update(variation_weight_params)
        format.html { redirect_to @variation_weight, notice: "Variation weight was successfully updated." }
        format.json { render :show, status: :ok, location: @variation_weight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @variation_weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variation_weights/1 or /variation_weights/1.json
  def destroy
    @variation_weight.destroy
    respond_to do |format|
      format.html { redirect_to variation_weights_url, notice: "Variation weight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation_weight
      @variation_weight = VariationWeight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variation_weight_params
      params.require(:variation_weight).permit(:weight, :date)
    end
end

app/helpers/variation_weights_helper.rb
module VariationWeightsHelper
end

app/views/variation_weights/_form.html.erb
<%= simple_form_for(@variation_weight) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <input type="hidden" name="variation_weigths[person_id]" value="<%= current_user.id %>">
  <input type="hidden" name="variation_weights[date]" value="<%= DateTime.current %>">

  <div class="field m-lg-2">
    <%= f.label "Peso atual:" %>
    <%= f.text_field :weight %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"Registro do peso",  class: "btn btn-primary"%>
  </div>
<% end %>

app/views/variation_weights/edit.html.erb
<h1>Editing Variation Weight</h1>

<%= render 'form', variation_weight: @variation_weight %>

<%= link_to 'Show', @variation_weight %> |
<%= link_to 'Back', variation_weights_path %>

app/views/variation_weights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variation Weights</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variation_weights.each do |variation_weight| %>
      <tr>
        <td><%= variation_weight.weight %></td>
        <td><%= variation_weight.date %></td>
        <td><%= link_to 'Show', variation_weight %></td>
        <td><%= link_to 'Edit', edit_variation_weight_path(variation_weight) %></td>
        <td><%= link_to 'Destroy', variation_weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variation Weight', new_variation_weight_path %>

app/views/variation_weights/new.html.erb
<h1>Registro de peso</h1>

<%= render 'form', variation_weight: @variation_weight %>

<%= link_to 'Back', dashboard_path(current_user&.person&.id), class: "btn btn-link" %>

app/views/variation_weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @variation_weight.weight %>
</p>

<p>
  <strong>Date:</strong>
  <%= @variation_weight.date %>
</p>

<%= link_to 'Edit', edit_variation_weight_path(@variation_weight) %> |
<%= link_to 'Back', variation_weights_path %>