config/routes.rb
# == Route Map
#
Rails.application.routes.draw do
  resources :variation_weights
  get "welcome/index"

  root "welcome#index"
  get "cadastrando_dados", to: "welcome#create_person", as: :first_login

  get "dashboard/:id", to: "dashboard#index", as: :dashboard
  get "dashboard/:id/diet_menu", to: "dashboard#menu_diet", as: :diet_dashboard

  resources :people
  resources :meals
  resources :diets

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: :create_person

  def index
  end

  def create_person

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/create_person.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: #7CFC00">
    <div class="container">
      <form class="form-inline">
        <div class="d-inline">
          <h1 class=" mr-sm-2" > Nome do app </h1>
          <% if user_signed_in? %>
            <%= "bem vindo #{current_user&.person&.name}" %>
          <% end %>
        </div>
      </form>
    </div>
  </nav>

  <div>
    <% if current_user.person.nil? %>
      <div class="container">
        <h7>vejo que é novo aqui no sistema, clique no botão abaixo para terminar o seu registro :D</h7>

        <div class="mt-2 mb-2">
          <%= button_to "Registrar-se", new_person_path, method: :get, class: "btn btn-primary" %>
        </div>
        <div>
          <%= button_to "logout", destroy_user_session_path, method: :delete, class:"btn btn-primary" %></a>
        </div>
      </div>
    <% else %>
      <div>
        <h4> mensagem motivacional </h4>
        <%= button_to "redirecionar para dashboard", diet_dashboard_path(current_user&.id), method: :get, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container text-center">
  <div class="col-lg-11 col-lg-offset-12">
    <td class="mt-6">
      <h1>Seja muito bem vindo</h1>
    </td>

    <% unless user_signed_in? %>
      <div class="btn-group">
        <ul>
          <label>
            <%= button_to "login", first_login_path, method: :get, class:"btn btn-primary" %>
          </label>
          <label>
            <%= button_to "Cadastrar-se", new_user_registration_path, method: :get, class:"btn link" %>
          </label>
        </ul>
      </div>
    <% else %>
      <td class="text-center">
        <%= button_to "logout", destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
      </td>
      <% if current_user.person.nil?%>
        <%= button_to "login", first_login_path, method: :get, class:"btn btn-primary" %>
      <% else %>
        <%= button_to "login", dashboard_path(current_user&.id), method: :get, class:"btn btn-accept" %>
      <% end %>
    <% end %>

  </div>
</div>