config/routes.rb
# == Route Map
#
Rails.application.routes.draw do
  resources :variation_weights
  get "welcome/index"

  root "welcome#index"
  get "cadastrando_dados", to: "welcome#create_person", as: :first_login

  get "dashboard/:id", to: "dashboard#index", as: :dashboard
  get "dashboard/:id/diet_menu", to: "dashboard#menu_diet", as: :diet_dashboard

  resources :people
  resources :meals
  resources :diets

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/diet.rb
# == Schema Information
#
# Table name: diets
#
#  id           :bigint           not null, primary key
#  person_id    :integer
#  initial_date :datetime
#  final_date   :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Diet < ApplicationRecord
  extend Enumerize

  enumerize :gender, in: {
    active: "Ativo",
    deactive: "inativo"
  }, scope: true, predicates: true, default: :inativo

  belongs_to :person, foreign_key: "person_id"

  has_many :meals

  validate :travel_in_time?
  validate :second_travel?
  validates :initial_date, presence: true
  validates :final_date, presence: true

  def travel_in_time?
    if initial_date < DateTime.current
      errors.add("isso só é possivel se você tiver uma maquina do tempo")
    end
  end

  def second_travel?
    if final_date < initial_date
      errors.add("isso só é possivel se você tiver uma maquina do tempo")
    end
  end

  def active_diet
    if DateTime.current <= final_date && DateTime.current >= initial_date
      @diet.status = "ativo"
    end
  end

end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :set_diet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @diets = Diet.all
  end

  def show
  end

  def new
    @diet = Diet.new
  end

  def edit
  end

  def create
    @diet = Diet.new(diet_params)

    respond_to do |format|
      if @diet.save
        format.html { redirect_to @diet, notice: "Diet was successfully created." }
        format.json { render :show, status: :created, location: @diet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @diet.update(diet_params)
        format.html { redirect_to @diet, notice: "Diet was successfully updated." }
        format.json { render :show, status: :ok, location: @diet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @diet.destroy
    respond_to do |format|
      format.html { redirect_to diets_url, notice: "Diet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_diet
      @diet = Diet.find(params[:id])
    end

    def diet_params
      params.require(:diet).permit(:person_id, :initial_date, :final_date)
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_form.html.erb
<%= form_with(model: diet) do |form| %>
  <% if diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
        <% diet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" name="diet[person_id]" value="<%= current_user.id %>">

  <div class="field m-lg-2">
    <%= form.label "Data inicial:" %>
    <%= form.date_field :initial_date, as: :date, value: form.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
  </div>

  <div class="field m-lg-2">
    <%= form.label "Data final" %>
    <%= form.date_field :final_date, as: :date, value: form.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<h1>Editing Diet</h1>

<%= render 'form', diet: @diet %>

<%= link_to 'Show', @diet %> |
<%= link_to 'Back', diets_path %>

app/views/diets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dietas</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Initial date</th>
      <th>Final date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.person_id %></td>
        <td><%= diet.initial_date %></td>
        <td><%= diet.final_date %></td>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>Nova Dieta</h1>

<%= render 'form', diet: @diet %>

<%= button_to "Voltar", diet_dashboard_path(current_user&.person&.id), method: :get %>

app/views/diets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @diet.person_id %>
</p>

<p>
  <strong>Initial date:</strong>
  <%= @diet.initial_date %>
</p>

<p>
  <strong>Final date:</strong>
  <%= @diet.final_date %>
</p>

<%= link_to 'Edit', edit_diet_path(@diet) %> |
<%= link_to 'Back', diets_path %>